### PR TITLE
RedHat support

### PR DESCRIPTION
**Pull request by philicious**
Tested your module on CentOS6 and found its partial RedHat support not working:
- Standard Config path for Redhat should be /etc/cassandra/conf/ not /etc/cassandra/ 
- File permissions fixed to cassandra:cassandra, otherwise data/log dir/files are wrong
- python-cql is called python26-cql on Redhat

You still have to take care of /etc/alternatives/cassandra pointing to the correct config path yourself by alternatives --install ....

### CODE REVIEW

**Comment by dkerwin** [comment]
Thanks for your effort to support rh based distributions. 
Please provide/update tests to reflect your changes and make the build pass. It cannot be merged before that.

**Comment by philicious** [comment]
@dkerwin I fixed the specs. Tests are passing locally and on Travis. However Travis' tests exit with status 1 but doesnt report errors. 
~~I am clueless~~ @joschi oh shame on me, missed that

**Comment by joschi** [comment]
Take a look at the output of the Travis CI job at [line 114](https://travis-ci.org/smarchive/puppet-cassandra/jobs/8164386#L114).

**Comment by joschi** [comment]
Thanks a lot!

**Pull request merged**
